### ISSUE TITLE
🛑 MonkeyTest3 Response Service is down

### ISSUE THREAD

**Issue by hadiel05** [hadiel05/upptime#26]
In [`43073a1`](https://github.com/hadiel05/upptime/commit/43073a147077ca264ddd356df4c15baacdf465ae
), MonkeyTest3 Response Service (http://mt3-responsesvc-vip.w8.jungle.tech/status) was **down**:
- HTTP code: 0
- Response time: 0 ms

**Comment by geleman** [comment]
I'm on it
